set(PROJECT_NAME "TestExecutor")
message(STATUS "PROJECT_NAME: ${PROJECT_NAME}")

set(DestinationDir ${CMAKE_SOURCE_DIR}/dist)
message(STATUS "DestinationDir: ${DestinationDir}")

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_C_STANDARD 11)

set(PRJ_QT "Qt6")

if(UNIX)
    set(MAIN_DEVEL_DIR "/home/dima")
    set(MAIN_QT_DIR ${MAIN_DEVEL_DIR}/opt/Qt/6.1.0)
    set(LOCAL_DEVEL_DIR ${MAIN_DEVEL_DIR}/local)
    set(PRJ_BOOST_VERSION "1.76")
    set(ENV{BOOST_INCLUDEDIR} ${LOCAL_DEVEL_DIR}/boost-${PRJ_BOOST_VERSION}/include)
    set(ENV{BOOST_LIBRARYDIR} ${LOCAL_DEVEL_DIR}/boost-${PRJ_BOOST_VERSION}/lib)
    set(ENV{OPENSSL_ROOT_DIR} ${LOCAL_DEVEL_DIR})
    set(UNIX_QT_PATH ${MAIN_QT_DIR}/gcc_64)
elseif(MSVC)
    set(MAIN_DEVEL_DIR "d:/usr")
    set(MAIN_QT_DIR "d:/Qt/6.1.0")
    set(PRJ_BOOST_VERSION "1.76")
    set(ENV{BOOST_INCLUDEDIR} ${LOCAL_DEVEL_DIR}/include/boost-${PRJ_BOOST_VERSION}/include)
    set(Boost_COMPILER "vc142")
    set(MSVC_QT_PATH ${MAIN_QT_DIR}/msvc2019_64)
elseif(MINGW)
    set(MAIN_DEVEL_DIR "d:/usr")
    set(MAIN_QT_DIR "d:/Qt/6.1.0")
    set(PRJ_BOOST_VERSION "1.76")
    set(ENV{BOOST_INCLUDEDIR} ${LOCAL_DEVEL_DIR}/include/boost-${PRJ_BOOST_VERSION}/include)
    set(Boost_COMPILER "mgw10")
    set(MINGW_QT_PATH ${MAIN_QT_DIR}/mingw81_64)
endif()

set(APP_ROOT_PATH "${CMAKE_CURRENT_SOURCE_DIR}")
set(APP_BUILD_PATH "${CMAKE_CURRENT_BINARY_DIR}")
message(STATUS "APP_ROOT_PATH: ${APP_ROOT_PATH}")
message(STATUS "APP_BUILD_PATH: ${APP_BUILD_PATH}")
set(THIRD_PARTY_LIB_PATH "${APP_BUILD_PATH}/third_party")
message(STATUS "THIRD_PARTY_LIB_PATH: ${THIRD_PARTY_LIB_PATH}")